### ISSUE TITLE
Lock Workstation Named Incorrectly

### ISSUE THREAD

**Issue by philippatelis** [krabs-github/com.krabs.windowsshutdownmenu.sdPlugin#1]
Just installed v1.0.7
The **Lock Workstation** icon is labelled as **Shutdown**.
The command is correct, but just has the incorrect name.

**Comment by krabs-github** [comment]
Thank you. I will fix it as soon as possible!

**Comment by krabs-github** [comment]
The issue has been fixed. I did not increment the version # however, because I had just submitted to Elgato for the store.  You can delete the plugin and reinstall 1.0.7 if you would like and it will fix the issue if you did not fix it yourself already.
