### ISSUE TITLE
Soundboard Action Hardcoded Path

### ISSUE THREAD

**Issue by philippatelis** [krabs-github/com.krabs.windowsshutdownmenu.sdPlugin#2]
Hey there - another issue - The sound icon (mp3) associated with the back button is hardcoded to your "krabs" windows profile.

![Stream-Deck-Config-Issue](https://user-images.githubusercontent.com/59756127/132936135-46c4ea8e-d362-40f5-b743-ecdf61c07ea1.jpg)

**Comment by krabs-github** [comment]
Thanks again, Phillipp.
I have updated the plugin to version 1.0.9 with several changes:
- Refactored shutdown and reboot behavior and timing.
- Fixed profile redirects to point to "Default Profile" in the XL version.
- Minor Bug fixes
- Removed hardcoded soundboard call (reported by philippatelis)

Please let me know if you see any other issues. Your input has been very helpful.
